server:
  port: 8081

spring:
  profiles:
    default: dev

  redis:
    timeout: 10000ms
    jedis:
      enabled: false

  output:
    ansi:
      enabled: always

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
