server:
  port: {WORKER_SERVER_PORT}

spring:
  datasource:
    data:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${DB_MARIADB_HOST}:${DB_MARIADB_PORT}/${DB_MARIADB_NAME}?useSSL=false&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
      username: ${DB_MARIADB_USERNAME}
      password: ${DB_MARIADB_PASSWORD}
    meta:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${DB_MARIADB_HOST}:${DB_MARIADB_PORT}/${DB_MARIADB_NAME_META}?useSSL=false&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
      username: ${DB_MARIADB_USERNAME}
      password: ${DB_MARIADB_USERNAME}

  redis:
    host: ${DB_REDIS_HOST}
    port: ${DB_REDIS_PORT}
    timeout: 10000ms
    jedis:
      enabled: false

  data:
    mongodb:
      uri: mongodb://${DB_MONGO_USERNAME}:${DB_MONGO_PASSWORD}@mongodb:${DB_MONGO_PORT}/${DB_MONGO_DATABASE}?authSource=admin

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
      sqs:
        queue:
          new_webtoon: $(AWS_SQS_WEBTOON_REQUEST)
          create-webtoon: ${AWS_SQS_CREATE_WEBTOON}
          update-webtoon: ${AWS_SQS_UPDATE_WEBTOON}
        auto-create: false
        enabled: false
