server:
  port: 8082

spring:
  config:
    import: optional:file:.env

  datasource:
    data:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/toonpick-database?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: root
      password: 1234
    meta:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/meta?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: root
      password: 1234

  data:
    redis:
      host: localhost
      port: 6380
      timeout: 10000ms
      jedis:
        enabled: false

    mongodb:
      uri: mongodb://localhost:27017/webtoon-db

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always


  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
      sqs:
        queue:
          webtoon-create-request: ${AWS_SQS_WEBTOON_CREATE_REQUEST}
          webtoon-update-request: ${AWS_SQS_WEBTOON_UPDATE_REQUEST}
          webtoon-create-complete: ${AWS_SQS_WEBTOON_CREATE_COMPLETE}
          webtoon-update-complete: ${AWS_SQS_WEBTOON_UPDATE_COMPLETE}
        auto-create: false
        enabled: false

logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
  file:
    name: logs/dev-application.log
    max-size: 10MB
