server:
  port: {WORKER_SERVER_PORT}

spring:
  datasource:
    data:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${DB_MARIADB_HOST}:${DB_MARIADB_PORT}/${DB_MARIADB_NAME}?useSSL=false&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul{DB_MARIADB_ADDITIONAL_PARAMS}
      username: ${DB_MARIADB_USERNAME}
      password: ${DB_MARIADB_PASSWORD}
    meta:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${DB_MARIADB_HOST}:${DB_MARIADB_PORT}/${DB_MARIADB_NAME_META}?useSSL=false&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul{DB_MARIADB_ADDITIONAL_PARAMS}
      username: ${DB_MARIADB_USERNAME}
      password: ${DB_MARIADB_USERNAME}

  data:
    redis:
      host: ${DB_REDIS_HOST}
      port: ${DB_REDIS_PORT}
      timeout: 10000ms
      jedis:
        enabled: false

    mongodb:
      uri: mongodb://${DB_MONGO_USERNAME}:${DB_MONGO_PASSWORD}@mongodb:${DB_MONGO_PORT}/${DB_MONGO_DATABASE}?authSource=admin

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
      sqs:
        queue:
          webtoon-create-request: ${AWS_SQS_WEBTOON_CREATE_REQUEST}
          webtoon-update-request: ${AWS_SQS_WEBTOON_UPDATE_REQUEST}
          webtoon-create-complete: ${AWS_SQS_WEBTOON_CREATE_COMPLETE}
          webtoon-update-complete: ${AWS_SQS_WEBTOON_UPDATE_COMPLETE}
        auto-create: false
        enabled: false


logging:
  level:
    org:
      springframework: INFO
  file:
    name: ${LOG_FILE_NAME}
    max-size: 10MB
