spring:
  datasource:
    data:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: ${SPRING_DATASOURCE_DATA_URL}
      username: ${SPRING_DATASOURCE_DATA_USERNAME}
      password: ${SPRING_DATASOURCE_DATA_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: 10000ms
    jedis:
      enabled: false

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
      sqs:
        queue:
          request:
            name: ${AWS_SQS_UPDATE_REQUEST_QUEUE_NAME}
            url: ${AWS_SQS_UPDATE_REQUEST_QUEUE_URL}
          response:
            name: ${AWS_SQS_UPDATE_RESPONSE_QUEUE_NAME}
            url: ${AWS_SQS_UPDATE_RESPONSE_QUEUE_URL}
        auto-create: false
        enabled: false
