server:
  port: {ADMIN_SERVER_PORT}

spring:
  datasource:
    data:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${DB_MARIADB_HOST}:${DB_MARIADB_PORT}/${DB_MARIADB_NAME}?useSSL=false&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul{DB_MARIADB_ADDITIONAL_PARAMS}
      username: ${DB_MARIADB_USERNAME}
      password: ${DB_MARIADB_PASSWORD}

  data:
    redis:
      host: ${DB_REDIS_HOST}
      port: ${DB_REDIS_PORT}
      timeout: 10000ms
      jedis:
        enabled: false

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
      sqs:
        queue:
          webtoon-create-request: ${AWS_SQS_WEBTOON_CREATE_REQUEST}
          webtoon-update-request: ${AWS_SQS_WEBTOON_UPDATE_REQUEST}
          webtoon-create-complete: ${AWS_SQS_WEBTOON_CREATE_COMPLETE}
          webtoon-update-complete: ${AWS_SQS_WEBTOON_UPDATE_COMPLETE}
        auto-create: false
        enabled: false


logging:
  level:
    org:
      springframework: INFO
  file:
    name: ${LOG_FILE_NAME}
    max-size: 10MB
