server:
  port: 8080

spring:
  profiles:
    default: dev

  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB


management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
